# Generated by Django 3.0.2 on 2020-01-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='product',
        ),
    ]
